package com.morecritters.mod.init;

import net.minecraft.core.registries.Registries;
import com.morecritters.mod.potion.AsphyxiationMobEffect;
import com.morecritters.mod.potion.BlossomingMobEffect;
import com.morecritters.mod.potion.BrainScentedMobEffect;
import com.morecritters.mod.potion.BrittlenessMobEffect;
import com.morecritters.mod.potion.CombustionMobEffect;
import com.morecritters.mod.potion.CrewsRumMobEffect;
import com.morecritters.mod.potion.ElectrocutedMobEffect;
import com.morecritters.mod.potion.EndfectedMobEffect;
import com.morecritters.mod.potion.EndsBlessingMobEffect;
import com.morecritters.mod.potion.EvolightenedMobEffect;
import com.morecritters.mod.potion.FrostbiteMobEffect;
import com.morecritters.mod.potion.GiftOfLifeMobEffect;
import com.morecritters.mod.potion.HallucinaziumMobEffect;
import com.morecritters.mod.potion.ImminentDeathMobEffect;
import com.morecritters.mod.potion.LeaperMobEffect;
import com.morecritters.mod.potion.MuscleAcheMobEffect;
import com.morecritters.mod.potion.OiledUpMobEffect;
import com.morecritters.mod.potion.RotCoveredMobEffect;
import com.morecritters.mod.potion.ShriekResistanceMobEffect;
import com.morecritters.mod.potion.SpawnMightshroomMobEffect;
import com.morecritters.mod.potion.SpawnNightshroomMobEffect;
import com.morecritters.mod.potion.SpookedMobEffect;
import com.morecritters.mod.potion.StagnationMobEffect;
import com.morecritters.mod.potion.StunnedMobEffect;
import com.morecritters.mod.potion.SwimmerMobEffect;
import com.morecritters.mod.potion.TrembleMobEffect;
import com.morecritters.mod.potion.UnderControlMobEffect;
import com.morecritters.mod.potion.WarptrapDiggerMobEffect;
import com.morecritters.mod.potion.WebbedMobEffect;
import net.minecraft.world.effect.MobEffect;
import net.neoforged.neoforge.registries.DeferredRegister;

import net.neoforged.neoforge.registries.DeferredHolder;

public class MoreCrittersModMobEffects {
    public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(Registries.MOB_EFFECT, "more_critters");
    public static final DeferredHolder<MobEffect, MobEffect> FROSTBITE = REGISTRY.register("frostbite", () -> new FrostbiteMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> SHRIEK_RESISTANCE = REGISTRY.register("shriek_resistance", () -> new ShriekResistanceMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> BLOSSOMING = REGISTRY.register("blossoming", () -> new BlossomingMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> ELECTROCUTED = REGISTRY.register("electrocuted", () -> new ElectrocutedMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> STAGNATION = REGISTRY.register("stagnation", () -> new StagnationMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> MUSCLE_ACHE = REGISTRY.register("muscle_ache", () -> new MuscleAcheMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> BRITTLENESS = REGISTRY.register("brittleness", () -> new BrittlenessMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> HALLUCINAZIUM = REGISTRY.register("hallucinazium", () -> new HallucinaziumMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> ASPHYXIATION = REGISTRY.register("asphyxiation", () -> new AsphyxiationMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> WARPTRAP_DIGGER = REGISTRY.register("warptrap_digger", () -> new WarptrapDiggerMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> ENDS_BLESSING = REGISTRY.register("ends_blessing", () -> new EndsBlessingMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> IMMINENT_DEATH = REGISTRY.register("imminent_death", () -> new ImminentDeathMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> GIFT_OF_LIFE = REGISTRY.register("gift_of_life", () -> new GiftOfLifeMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> TREMBLE = REGISTRY.register("tremble", () -> new TrembleMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> STUNNED = REGISTRY.register("stunned", () -> new StunnedMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> SPAWN_MIGHTSHROOM = REGISTRY.register("spawn_mightshroom", () -> new SpawnMightshroomMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> ROT_COVERED = REGISTRY.register("rot_covered", () -> new RotCoveredMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> SPAWN_NIGHTSHROOM = REGISTRY.register("spawn_nightshroom", () -> new SpawnNightshroomMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> WEBBED = REGISTRY.register("webbed", () -> new WebbedMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> COMBUSTION = REGISTRY.register("combustion", () -> new CombustionMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> LEAPER = REGISTRY.register("leaper", () -> new LeaperMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> SWIMMER = REGISTRY.register("swimmer", () -> new SwimmerMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> SPOOKED = REGISTRY.register("spooked", () -> new SpookedMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> BRAIN_SCENTED = REGISTRY.register("brain_scented", () -> new BrainScentedMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> ENDFECTED = REGISTRY.register("endfected", () -> new EndfectedMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> UNDER_CONTROL = REGISTRY.register("under_control", () -> new UnderControlMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> OILED_UP = REGISTRY.register("oiled_up", () -> new OiledUpMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> EVOLIGHTENED = REGISTRY.register("evolightened", () -> new EvolightenedMobEffect());
    public static final DeferredHolder<MobEffect, MobEffect> CREWS_RUM = REGISTRY.register("crews_rum", () -> new CrewsRumMobEffect());
}
